# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/319bb1db-f22e-4548-8569-0cfdb522ee2f";
      fsType = "btrfs";
      options = [ "subvol=@environments/gnome" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/319bb1db-f22e-4548-8569-0cfdb522ee2f";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/cache/pacman/pkg" =
    { device = "/dev/disk/by-uuid/319bb1db-f22e-4548-8569-0cfdb522ee2f";
      fsType = "btrfs";
      options = [ "subvol=@pkg" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/319bb1db-f22e-4548-8569-0cfdb522ee2f";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D9B2-2A09";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/richi" =
    { device = "/dev/disk/by-uuid/d6716272-0977-4469-bf4c-eedb6d465a34";
      fsType = "btrfs";
      options = [ "subvol=richi" ];
    };

  boot.initrd.luks.devices."home-richi".device = "/dev/disk/by-uuid/5e96e7d1-c056-4da9-aa64-c156f148727f";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
